on:
  schedule:
    - cron: "0 18 * * *" # JST 03:00

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: hxrxchang/gtd-manager@v0.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_ZONE: "Asia/Tokyo" #オプショナル。デフォルトはUTC。
          LABEL: "日報" #オプショナル。ラベル名を指定できる。
